spring:
  application:
    name: EventManagement
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    show-sql: true

server:
  port: 8090
  servlet:
    context-path: /api